name: mercury-lflist-download

on:
  workflow_dispatch:

jobs:
 
  download:
    name: Download LFLIST
    runs-on: ubuntu-latest
    steps:
      - name: Create directories
        run: |
          mkdir -p projectignis
          mkdir -p koishi

      - name: Download from ProjectIgnis
        run: |
          curl -L https://github.com/ProjectIgnis/LFLists/archive/refs/heads/master.zip -o projectignis/LFLists.zip
          unzip projectignis/LFLists.zip -d projectignis
          rm projectignis/LFLists.zip

      - name: Download lflist.conf from YGOMobile
        run: |
          curl -L https://raw.githubusercontent.com/fallenstardust/YGOMobile-cn-ko-en/master/mobile/assets/data/conf/lflist.conf -o koishi/lflist.conf

      - name: Split lflist.conf into multiple files
        run: |
          year=$(date +"%Y")
          file_path="koishi/lflist.conf"
          output_dir="koishi"
          awk -v year="$year" -v output_dir="$output_dir" '
          BEGIN {RS="!"; FS="\n"; ORS=""}
          {
            if ($1 ~ year) {
              sub(/^[ \t]+|[ \t]+$/, "", $1)
              file_name=output_dir"/"substr($1, 2)".conf"
              print "#[" substr($1, 2) "]\n!" $0 > file_name
            }
          }
          ' $file_path

      - name: List files in koishi directory
        run: ls -l koishi

      - name: Display content of one file
        run: cat koishi/2024.7.conf