name: mercury-lflist-test

on:
  workflow_dispatch:

jobs:
 
  download:
    name: Download LFLIST
    runs-on: ubuntu-latest
    steps:
      - name: Create directories
        run: |
          mkdir -p projectignis
          mkdir -p koishi

      - name: Clone LFLists repository from ProjectIgnis
        run: |
          git clone https://github.com/ProjectIgnis/LFLists projectignis

      - name: Download lflist.conf from YGOMobile
        run: |
          curl -L https://raw.githubusercontent.com/fallenstardust/YGOMobile-cn-ko-en/master/mobile/assets/data/conf/lflist.conf -o koishi/lflist.conf

      - name: Split lflist.conf into multiple files
        run: |
          year=$(date +"%Y")
          file_path="koishi/lflist.conf"
          output_dir="koishi"
          awk -v year="$year" -v output_dir="$output_dir" '
          /^!/{if (out) close(out); out=""; if ($1 ~ "^!" year) {filename=substr($0, 2) ".KS.lflist.conf"; out=output_dir "/" filename; print "#[" substr($0, 2) "]\n" $0 > out; next}}
          out {print >> out}' $file_path

      - name: List files in koishi directory
        run: ls -l koishi

      - name: Remove lflist.conf
        run: rm koishi/lflist.conf

      - name: Upload Koishi artifacts
        uses: actions/upload-artifact@v4
        with:
          name: koishi-files
          path: koishi/

      - name: Upload Project Iginis artifacts
        uses: actions/upload-artifact@v4
        with:
            name: projectignis-files
            path: projectignis/

  hash:
    name: Process LFLIST
    needs: download
    runs-on: ubuntu-latest
    steps:
      - name: Download koishi artifacts
        uses: actions/download-artifact@v4
        with:
          name: koishi-files
          path: koishi/

      - name: Download projectignis artifacts
        uses: actions/download-artifact@v4
        with:
          name: projectignis-files
          path: projectignis/

      - name: Create necessary directories
        run: mkdir -p new

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process banlists and generate hashes
        run: |
          cat << 'EOF' > process_banlists.js
          const fs = require('fs');
          const path = require('path');

          class BanList {
            constructor() {
              this.forbidden = [];
              this.limited = [];
              this.semiLimited = [];
              this.all = [];
              this._hash = 0x7dfcee6a;
              this.name = null;
            }

            add(cardId, quantity) {
              if (isNaN(cardId)) {
                return;
              }

              if (quantity === 0) {
                this.forbidden.push(cardId);
              }

              if (quantity === 1) {
                this.limited.push(cardId);
              }

              if (quantity === 2) {
                this.semiLimited.push(cardId);
              }

              if (quantity === 3) {
                this.all.push(cardId);
              }

              this._hash =
                this._hash ^
                ((((cardId >>> 0) << 18) >> 0) | (cardId >> 14)) ^
                ((((cardId >>> 0) << (27 + quantity)) >>> 0) | (cardId >>> (5 - quantity)));
            }

            setName(name) {
              this.name = name;
            }

            whileListed() {
              // Implement any necessary logic for whileListed
            }

            load(filePath) {
              const lines = fs.readFileSync(filePath, "utf-8").split("\n");
              for (const line of lines) {
                if (!line) {
                  continue;
                }

                if (line.startsWith("$whitelist")) {
                  this.whileListed();
                }

                if (line.startsWith("#")) {
                  continue;
                }

                if (line.startsWith("!")) {
                  this.setName(line.substring(1).trim());
                }

                if (!line.includes(" ")) {
                  continue;
                }

                if (this.name === null) {
                  continue;
                }

                const [cardId, quantity] = line.split(" ");
                this.add(Number(cardId), Number(quantity));
              }
            }

            updateFile(filePath) {
              const lines = fs.readFileSync(filePath, "utf-8").split("\n");
              const updatedLines = lines.map(line => {
                if (line.startsWith("#[")) {
                  return line.replace(/#\[([^\]]+)\]/, '#[$1 KS]');
                } else if (line.startsWith("!")) {
                  return line.replace(/^!(.+)$/, '!$1 KS');
                }
                return line;
              });
              fs.writeFileSync(filePath, updatedLines.join("\n"), "utf-8");
            }
          }

          function processBanlists(dir) {
            const files = fs.readdirSync(dir);
            const hashes = [];

            files.forEach(file => {
              const filePath = path.join(dir, file);
              if (fs.lstatSync(filePath).isFile() && file.endsWith('.conf')) {
                const banList = new BanList();
                banList.load(filePath);
                console.log(`Path: ${filePath}`);
                console.log(`Banlist: ${banList.name}, Hash: ${banList._hash}`);
                hashes.push({ hash: banList._hash, file: file });
              }
            });

            return hashes;
          }

          const projectignisDir = 'projectignis';
          const koishiDir = 'koishi';

          const projectignisHashes = processBanlists(projectignisDir);
          const koishiHashes = processBanlists(koishiDir);

          const newFilesDir = 'new';

          koishiHashes.forEach(({ hash, file }) => {
            if (!projectignisHashes.some(item => item.hash === hash)) {
              const filePath = path.join(koishiDir, file);
              const newFilePath = path.join(newFilesDir, file);

              // Copy the file to the new directory
              fs.copyFileSync(filePath, newFilePath);

              // Update the copied file
              const banList = new BanList();
              banList.updateFile(newFilePath);
            }
          });
          EOF

          # Run the Node.js script
          node process_banlists.js

          # Clean up the generated JavaScript file
          rm process_banlists.js

      - name: List files in new directory
        run: ls -l new